config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    unauthenticated :user do
        root to: "devise/sessions#new",as: :unauthenticated_root #设定登录页为系统默认首页
    end
    authenticated :user do
        root to: "store#index",as: :authenticated_root #设定系统登录后首页
    end

    authenticated :admin_user do
       root to: "admin#index"
    end
end
  get 'cookies/index'
  get 'cakes/index'
  get 'chocolate/index'
  get 'carts/delete_one_pro'
  get 'carts/order_info'
  post 'orders/new_order'
  get 'orders/index'
  resources :line_items
  resources :carts
  root 'store#index', as:  'store_index'
  resources :products



  get 'contact', to: 'store#contact'
  post 'request_contact', to: 'store#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
  current_item
 end

 def total_price
   line_items.to_a.sum { |item| item.total_price }
 end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[index show edit update destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /carts or /carts.json
  def index   
    @cart = Cart.find(session[:cart_id])
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create

    @cart = Cart.new(cart_params)
    @cart.user_id = current_user.id

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end
  def delete_one_pro

    if LineItem.find(params[:item_id]).delete
      redirect_to "/carts/#{params[:cart_id]}"
    end
  end
    def order_info
      lineids = params[:cart_ids].split("||")
      @items = LineItem.where(id:lineids)
    end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: 'Your cart is currently empty.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      begin
        @cart = Cart.find(session[:cart_id])
      rescue ActiveRecord::RecordNotFound
        @cart = Cart.create
        @cart.user_id = current_user.id
        session[:cart_id] = @cart.id
      end
    end

    def invalid_cart
      redirect_to store_index_url, notice: 'Invalid Cart'
    end
    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> 
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>


<center>
 <div class=" cartB">
   <br>
   <br>
   <br>
   <br>
   <br>
   <br>
   <h2 class="candyt"> Your SweetDream Cart</h2>
   <br>
    <form class="checkout" action="index.html" method="post">
    <table style="font-weight:bold; ">
      <% if !@cart.nil? %>
        <% @cart.line_items.each do |item|%>
         <tr class="cartsline">
           <td>&nbsp;<%= item.quantity %> &times;</td>
           <td><%= item.product.title %></td>
            <td class='item_price'><%= number_to_currency(item.total_price) %> </td>
            <td class="deletepro">
              <a href="carts/delete_one_pro?item_id=<%= item.id %>&cart_id=<%=item.cart_id%>">delete</a><!--give a link for delete, so i need to find what that i need to delete, so the index of item will be the ID,then make sure the id not only are item ,but also are in cart.-->
            </td>
         </tr>
        <% end %>
      <% end %>


      <tr class="total_line" style="height: 30px;">
        <td colspan="2">Total</td>
        <td class="total_cell">
          <%= number_to_currency(@cart.total_price) rescue 0 %>
        </td>
      </tr>
      <tr>
        <td class="empty">
        <!--<%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?' } %> -->
        </td>

        <td>
          <button class="bottomPay">
            <!--it can be seen that PLUCK method select the "id" of each piece of data in the line_items table as the array. join table query ,  rescue ""-->
            <a href="/carts/order_info?cart_ids=<%= @cart.line_items.pluck("id").join("||") %>">Pay</a>
          </button>
       </td>

      </tr>
    </table>
    </form>
  </div>

</center>

<div class="container-fluid text-center bg-grey">
  <h4>In the future</h4>
  <div class="row text-center" style="background-color: #dedae0">
    <div class="col-sm-4" >
      <div class="thumbnail" style="background-color: #e3c1f7">
        <img src="assets/lollipop.webp" alt="" width="400" height="300">
        <p><strong>lollipop</strong></p>

      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail" style="background-color: #e3c1f7">
        <img src="assets/DIY.jpg" alt="" width="400" height="300">
        <p><strong>DIY Candy</strong></p>

      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail" style="background-color: #e3c1f7">
        <img src="assets/milkshake1.jpg" alt="" width="400" height="300">
        <p><strong>Milk shake</strong></p>

      </div>
    </div>
  </div>
</div>

app/views/carts/new.html.erb
<div class="">
  
  <h1>New Cart</h1>

  <%= render 'form', cart: @cart %>

  <%= link_to 'Back', carts_path %>
</div>

app/views/carts/order_info.html.erb

</style>
<div class="container">
	<div class="header">
		<h1>order detail</h1>
	</div>
	<hr>
	<div class="product_list">
		<h3>product lists</h3>
		<hr>
		<div class="list">
			<% total_price = 0 %>
			<ul class="order_ac">
				<% @items.each do |item| %>
					<li class="order_acTitle ">Title:<label class="product_title"><%= item.product.title %></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						Count:<label class="product_title"><%= item.quantity %></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
						<% price = item.total_price %>
						<% total_price = total_price + price %>
						Price:<label class="product_title"><%= number_to_currency(price) %></label> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					</li>
				<% end %>
				<li>total price: <label class="product_title"><%= number_to_currency(total_price) %></label></li>
			</ul>
		</div>
	</div>
	<hr>

	<div class="delivered">
		<h2>Sweets  delivered information  </h2>
			<hr>
			<form action="/orders/new_order" method="post">
				<input type="text" hidden name="item_ids" value="<%= params[:cart_ids] %>">
				<div class="">

				</div>
				<br>
				<div class="contact1">
					<label>name:</label>
					<input type="text" name="name" class="contact_input">
				</div>
				<br>
				<div class="contact">
					<label>phone:</label>
					<input type="text" name="phone" class="contact_input">
				</div>
				<br>
				<div class="contact">
					<label>address:</label>
					<input type="text" name="address" class="contact_input">
				</div>
				<br>
				<div class="picture">
					<img src="https://media.istockphoto.com/photos/closeup-portrait-of-funny-ginger-cat-wearing-sunglasses-isolated-on-picture-id1253696116?k=20&m=1253696116&s=170667a&w=0&h=Cm_OrKx4P_IN3dfzKbpaLUs5yW8B3zZaFYJNNFrHhLA=" alt="">
				</div>

				<br><br><br><br><br><br><br><br>
				<button class="submit_or"type="submit" >submit order</button>
			</form>
	</div>
	<hr>
</div>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>


<center>
 <div class=" cartB">
   <br>
   <br>
   <br>
   <br>
   <br>
   <br>
   <h2 class="candyt"> Your SweetDream Cart</h2>
   <br>
    <form class="checkout" action="index.html" method="post">
      <p id="notice"><%= notice %></p>

        <table style="font-weight:bold;">
          <% @cart.line_items.each do |item|%>
             <tr style="border-bottom:1px solid #BBB;height: 30px;">
               <td>&nbsp;<%= item.quantity %> &times;</td>
               <td><%= item.product.title %></td>
                <td class='item_price'><%= number_to_currency(item.total_price) %> </td>
                <td> <a href="http://localhost:3000/carts/delete_one_pro?item_id=<%= item.id %>&cart_id=<%=item.cart_id%>">delete</a></td>
             </tr>
            <% end %>


          <tr class="total_line" style="height: 30px;">
            <td colspan="2">Total</td>
            <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
          </tr>
          <tr>
            <td>
              <!--<%= button_to 'Empty cart', @cart, method: :delete, data: { confirm: 'Are you sure?' } %>-->

            </td>
            <td>
              <button class="bottomPay">
                <a href="/carts/order_info?cart_ids=<%= @cart.line_items.pluck("id").join("||") %>">Pay</a>
              </button>

            </td>
          </tr>
        </table>

    </form>
  </div>

</center>
<div class="container-fluid text-center bg-grey">
  <h4>In the future</h4>
  <div class="row text-center" style="background-color: #dedae0">
    <div class="col-sm-4" >
      <div class="thumbnail" style="background-color: #e3c1f7">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkyTz8fyxqn0WMqtP5og1TomcMQT8qv8N75Q&usqp=CAU " alt="" width="300" height="300">
        <p><strong>DIY</strong></p>

      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail" style="background-color: #e3c1f7">
        <img src="https://cdn.shopify.com/s/files/1/2725/9456/products/flavourtown-bakery-london-cakes_galaxy-cake_2048x2048.jpg?v=1583339986" alt="" width="300" height="100">
        <p><strong>color cake</strong></p>

      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail" style="background-color: #e3c1f7">
        <img src="https://bakingmischief.com/wp-content/uploads/2022/03/coffee-milkshake-square.jpg" alt="" width="300" height="200">
        <p><strong>Milk shake</strong></p>

      </div>
    </div>
  </div>
</div>