config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    unauthenticated :user do
        root to: "devise/sessions#new",as: :unauthenticated_root #设定登录页为系统默认首页
    end
    authenticated :user do
        root to: "store#index",as: :authenticated_root #设定系统登录后首页
    end

    authenticated :admin_user do
       root to: "admin#index"
    end
end
  get 'cookies/index'
  get 'cakes/index'
  get 'chocolate/index'
  get 'carts/delete_one_pro'
  get 'carts/order_info'
  post 'orders/new_order'
  get 'orders/index'
  resources :line_items
  resources :carts
  root 'store#index', as:  'store_index'
  resources :products



  get 'contact', to: 'store#contact'
  post 'request_contact', to: 'store#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.order(:title)
  end

  def contact

  end

  def request_contact
      name = params[:name]
      email = params[:email]
      telephone = params[:telephone]
      message = params[:message]

      if email.blank?
        flash[:alert] = I18n.t('store.request_contact.no_email')
      else
        ContactMailer.contact_email(email, name, telephone, message).deliver_now
        flash[:notice] = I18n.t('store.request_contact.email_sent')
      end

      redirect_to store_index_url

  end

end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/contact.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Please contact us</title>
    <link rel="contact" href="http://localhost:3000/contact">

  </head>
  <body >

    <center>
    <div class="form">
       <br>
       <br>
       <br>
       <br>
      <%= form_tag request_contact_path, method: 'post' do %>
         <%= label_tag :name, t('.name') %>
         <%= text_field_tag :name, '', title: t('.enter_name'), size: 50 %>

         <%= label_tag :email, t('.email') %>
         <%= email_field_tag :email, '', title: t('.enter_email'), size: 50 %>

         <%= label_tag :telephone, t('.telephone') %>
         <%= telephone_field_tag :telephone, '', title: t('.enter_telephone'), size: 50 %>

         <%= label_tag :message, t('.message') %>
         <%= text_field_tag :message, '', title: t('.enter_message'), size: 50 %>

         <%= submit_tag t('.submit') %>
        <% end %>
    </div>
    </center>
    <div class="container-fluid" style="background-color:#df5b6e">
      <div class="row">
        <div class="col-sm-8">
          <h2>About SweetDream</h2>
          <p>We are committed to bringing sweet food to the world..</p>
          <button class="btn btn-default btn-lg" href="http://localhost:3000">Get in Touch</button>
        </div>
        <div class="col-sm-4">
          <span class="glyphicon glyphicon-signal logo"></span>
        </div>
      </div>
    </div>

    <div class="container-fluid bg-grey" style="background-color:#ece6ed">
      <div class="row">
        <div class="col-sm-4">
          <span class="glyphicon glyphicon-globe logo"></span>
        </div>
        <div class="col-sm-8">
          <h2>Our Values</h2>
          <h4><strong>MISSION:</strong> TRY OUR BEST..</h4>
          <p><strong>VISION:</strong> MAKE EVERTHING PERFECT.</p>
        </div>
      </div>
    </div>





  </body>


</html>

app/views/store/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
  <body>
    <div class="jumbotron" >
      <div class="container text-center" >
        <img src="assets/storelogo.png" alt="">
        <h1 style="color:#77cce6" >Sweet Dream</h1>
        <div style="color:#3ead5c">This is a Big Big Welcome </div>
      </div>
    </div>


    <div class="row">
      <div class="">
        <% cache @products do %>
          <% @products.each do |product| %>
              <% cache product do %>


                        <div class="col-sm-4">
                          <div class="products" >


                            <div class="image">
                              <%= image_tag(product.image_url, width: 200, height: 200)  %>
                            </div>


                            <div class="title">
                                <%= product.title %>
                            </div>


                             <div class="description">
                               <%= sanitize(product.description) %>
                             </div>



                            <div class="shopping">
                              <div class="price" ><%= number_to_currency(product.price) %></div>
                              <div class="Cart">
                                <%= button_to 'Add to Cart', line_items_path(product_id: product) %>
                              </div>
                            </div>




                          </div>
                        </div>
                <% end %>
             <% end %>
         <% end %>

      </div>

    </div>
</body>
</html>